// click('header-signup');
// setInput(fullname,'fullname');
// setInput(email,'email');
// setInput(password,'password');
// click('do-signup');
// redirectToUrl(freeUrl);
// click('buy-this-course-button');
// redirectToUrl("https://www.udemy.com/complete-java-course-from-scratch/learn/v4/content");
// var elements = document.querySelectorAll('[aria-label="Course Progress"]');
// elements.forEach(function(elem){
// elem.click();
// });
// redirectToUrl("https://www.udemy.com/complete-java-course-from-scratch/learn/v4/content/reviews/1/?location=dh");
// click("review-star-input-5-label");
click('right-button');
checkAll(12);
checkAll(14);
click('right-button');
setInput(review,'public-review');
click('right-button');
click('right-button');